In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score

from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean

from imblearn.pipeline import Pipeline
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours

from imblearn.over_sampling import ADASYN
from collections import Counter
from sklearn.metrics import accuracy_score

from numpy.random import seed
seed(7)

from sklearn.model_selection import train_test_split

SEED = 123 #used to help randomly select the data points
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [2]:
df = pd.read_csv("combined_filtered_aug.csv") 
df.head(n=5)

,Unnamed: 0,_time,GreenRocket,Door1,Door2,LoadCell_R02,Potentiometer_R02,LoadCell_R03,Potentiometer_R03,LoadCell_R04,...,rolling_mean_Potentiometer_R04,expanding_mean_GreenRocket,expanding_mean_Door1,expanding_mean_Door2,expanding_mean_LoadCell_R02,expanding_mean_Potentiometer_R02,expanding_mean_LoadCell_R03,expanding_mean_Potentiometer_R03,expanding_mean_LoadCell_R04,expanding_mean_Potentiometer_R04
0,0,2023-09-19T14:21:53.393Z,1,0,0,1857,11866,1693,2390,2640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023-09-19T14:21:53.485Z,1,0,0,1862,11896,1679,2396,2643,...,NaN,1.0,0.0,0.0,1859.5,11881.000000,1686.000000,2393.000000,2641.500000,11881.500000
2,2,2023-09-19T14:21:53.582Z,1,0,0,1867,11957,1669,2379,2659,...,NaN,1.0,0.0,0.0,1862.0,11906.333333,1680.333333,2388.333333,2647.333333,11900.666667
3,3,2023-09-19T14:21:53.687Z,1,0,0,1886,11955,1699,2403,2612,...,NaN,1.0,0.0,0.0,1868.0,11918.500000,1685.000000,2392.000000,2638.500000,11908.500000
4,4,2023-09-19T14:21:53.793Z,1,0,0,1887,11966,1670,2388,2630,...,NaN,1.0,0.0,0.0,1871.8,11928.000000,1682.000000,2391.200000,2636.800000,11913.000000

In [3]:
df['Success'] = df['Success'].replace({1: 0, 0: 1})
df

,Unnamed: 0,_time,GreenRocket,Door1,Door2,LoadCell_R02,Potentiometer_R02,LoadCell_R03,Potentiometer_R03,LoadCell_R04,...,rolling_mean_Potentiometer_R04,expanding_mean_GreenRocket,expanding_mean_Door1,expanding_mean_Door2,expanding_mean_LoadCell_R02,expanding_mean_Potentiometer_R02,expanding_mean_LoadCell_R03,expanding_mean_Potentiometer_R03,expanding_mean_LoadCell_R04,expanding_mean_Potentiometer_R04
0,0,2023-09-19T14:21:53.393Z,1,0,0,1857,11866,1693,2390,2640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023-09-19T14:21:53.485Z,1,0,0,1862,11896,1679,2396,2643,...,NaN,1.000000,0.000000,0.000000,1859.500000,11881.000000,1686.000000,2393.000000,2641.500000,11881.500000
2,2,2023-09-19T14:21:53.582Z,1,0,0,1867,11957,1669,2379,2659,...,NaN,1.000000,0.000000,0.000000,1862.000000,11906.333333,1680.333333,2388.333333,2647.333333,11900.666667
3,3,2023-09-19T14:21:53.687Z,1,0,0,1886,11955,1699,2403,2612,...,NaN,1.000000,0.000000,0.000000,1868.000000,11918.500000,1685.000000,2392.000000,2638.500000,11908.500000
4,4,2023-09-19T14:21:53.793Z,1,0,0,1887,11966,1670,2388,2630,...,NaN,1.000000,0.000000,0.000000,1871.800000,11928.000000,1682.000000,2391.200000,2636.800000,11913.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216029,216029,2023-09-19T20:21:59.584Z,0,0,0,1888,2061,1676,2382,2604,...,11871.714286,0.027325,0.015229,0.018849,1869.839615,11245.814230,2760.599134,3642.971143,3006.628565,10718.385798
216030,216030,2023-09-19T20:21:59.686Z,0,0,0,1854,2061,1686,2404,2776,...,11868.571429,0.027325,0.015229,0.018849,1869.839542,11245.771713,2760.594160,3642.965408,3006.627498,10718.391166
216031,216031,2023-09-19T20:21:59.785Z,0,0,0,1859,2073,1685,2403,3218,...,11877.857143,0.027325,0.015229,0.018849,1869.839491,11245.729253,2760.589181,3642.959668,3006.628476,10718.396714
216032,216032,2023-09-19T20:21:59.887Z,0,0,0,1860,2067,1655,2385,2176,...,11878.285714,0.027325,0.015229,0.018849,1869.839446,11245.686765,2760.584064,3642.953845,3006.624631,10718.402202
216033,216033,2023-09-19T20:21:59.981Z,0,0,0,1883,2071,1680,2396,3437,...,11884.000000,0.027324,0.015229,0.018849,1869.839507,11245.644297,2760.579062,3642.948073,3006.626624,10718.407700

In [4]:
df['Success'].value_counts()

0    212296
1      3738
Name: Success, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216034 entries, 0 to 216033
Data columns (total 49 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Unnamed: 0                        216034 non-null  int64
 1   _time                             216034 non-null  object
 2   GreenRocket                       216034 non-null  int64
 3   Door1                             216034 non-null  int64
 4   Door2                             216034 non-null  int64
 5   LoadCell_R02                      216034 non-null  int64
 6   Potentiometer_R02                 216034 non-null  int64
 7   LoadCell_R03                      216034 non-null  int64
 8   Potentiometer_R03                 216034 non-null  int64
 9   LoadCell_R04                      216034 non-null  int64
 10  Potentiometer_R04                 216034 non-null  int64
 11  Anomally                          216034 non-null  int64
 12  Success                           216034 non-null  int64
 13  GreenRocket_pct_change            5974 non-null    float64
 14  Door1_pct_change                  3303 non-null    float64
 15  Door2_pct_change                  4079 non-null    float64
 16  LoadCell_R02_pct_change           216033 non-null  float64
 17  Potentiometer_R02_pct_change      216033 non-null  float64
 18  LoadCell_R03_pct_change           216033 non-null  float64
 19  Potentiometer_R03_pct_change      216033 non-null  float64
 20  LoadCell_R04_pct_change           216033 non-null  float64
 21  Potentiometer_R04_pct_change      216033 non-null  float64
 22  lag_GreenRocket                   216033 non-null  float64
 23  lag_Door1                         216033 non-null  float64
 24  lag_Door2                         216033 non-null  float64
 25  lag_LoadCell_R02                  216033 non-null  float64
 26  lag_Potentiometer_R02             216033 non-null  float64
 27  lag_LoadCell_R03                  216033 non-null  float64
 28  lag_Potentiometer_R03             216033 non-null  float64
 29  lag_LoadCell_R04                  216033 non-null  float64
 30  lag_Potentiometer_R04             216033 non-null  float64
 31  rolling_mean_GreenRocket          216028 non-null  float64
 32  rolling_mean_Door1                216028 non-null  float64
 33  rolling_mean_Door2                216028 non-null  float64
 34  rolling_mean_LoadCell_R02         216028 non-null  float64
 35  rolling_mean_Potentiometer_R02    216028 non-null  float64
 36  rolling_mean_LoadCell_R03         216028 non-null  float64
 37  rolling_mean_Potentiometer_R03    216028 non-null  float64
 38  rolling_mean_LoadCell_R04         216028 non-null  float64
 39  rolling_mean_Potentiometer_R04    216028 non-null  float64
 40  expanding_mean_GreenRocket        216033 non-null  float64
 41  expanding_mean_Door1              216033 non-null  float64
 42  expanding_mean_Door2              216033 non-null  float64
 43  expanding_mean_LoadCell_R02       216033 non-null  float64
 44  expanding_mean_Potentiometer_R02  216033 non-null  float64
 45  expanding_mean_LoadCell_R03       216033 non-null  float64
 46  expanding_mean_Potentiometer_R03  216033 non-null  float64
 47  expanding_mean_LoadCell_R04       216033 non-null  float64
 48  expanding_mean_Potentiometer_R04  216033 non-null  float64
dtypes: float64(36), int64(12), object(1)
memory usage: 80.8+ MB

In [6]:
# Remove time column
df = df.drop(['_time','Unnamed: 0'], axis=1)

In [7]:
df.replace([np.inf, -np.inf], 0, inplace=True)
df

,GreenRocket,Door1,Door2,LoadCell_R02,Potentiometer_R02,LoadCell_R03,Potentiometer_R03,LoadCell_R04,Potentiometer_R04,Anomally,...,rolling_mean_Potentiometer_R04,expanding_mean_GreenRocket,expanding_mean_Door1,expanding_mean_Door2,expanding_mean_LoadCell_R02,expanding_mean_Potentiometer_R02,expanding_mean_LoadCell_R03,expanding_mean_Potentiometer_R03,expanding_mean_LoadCell_R04,expanding_mean_Potentiometer_R04
0,1,0,0,1857,11866,1693,2390,2640,11855,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,0,1862,11896,1679,2396,2643,11908,0,...,NaN,1.000000,0.000000,0.000000,1859.500000,11881.000000,1686.000000,2393.000000,2641.500000,11881.500000
2,1,0,0,1867,11957,1669,2379,2659,11939,0,...,NaN,1.000000,0.000000,0.000000,1862.000000,11906.333333,1680.333333,2388.333333,2647.333333,11900.666667
3,1,0,0,1886,11955,1699,2403,2612,11932,0,...,NaN,1.000000,0.000000,0.000000,1868.000000,11918.500000,1685.000000,2392.000000,2638.500000,11908.500000
4,1,0,0,1887,11966,1670,2388,2630,11931,0,...,NaN,1.000000,0.000000,0.000000,1871.800000,11928.000000,1682.000000,2391.200000,2636.800000,11913.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216029,0,0,0,1888,2061,1676,2382,2604,11801,1,...,11871.714286,0.027325,0.015229,0.018849,1869.839615,11245.814230,2760.599134,3642.971143,3006.628565,10718.385798
216030,0,0,0,1854,2061,1686,2404,2776,11878,1,...,11868.571429,0.027325,0.015229,0.018849,1869.839542,11245.771713,2760.594160,3642.965408,3006.627498,10718.391166
216031,0,0,0,1859,2073,1685,2403,3218,11917,1,...,11877.857143,0.027325,0.015229,0.018849,1869.839491,11245.729253,2760.589181,3642.959668,3006.628476,10718.396714
216032,0,0,0,1860,2067,1655,2385,2176,11904,1,...,11878.285714,0.027325,0.015229,0.018849,1869.839446,11245.686765,2760.584064,3642.953845,3006.624631,10718.402202
216033,0,0,0,1883,2071,1680,2396,3437,11906,1,...,11884.000000,0.027324,0.015229,0.018849,1869.839507,11245.644297,2760.579062,3642.948073,3006.626624,10718.407700

In [8]:
X = df.drop(['Success','Anomally'], axis=1)
y = df['Success']

In [9]:
X
X=X.fillna(0)
X

,GreenRocket,Door1,Door2,LoadCell_R02,Potentiometer_R02,LoadCell_R03,Potentiometer_R03,LoadCell_R04,Potentiometer_R04,GreenRocket_pct_change,...,rolling_mean_Potentiometer_R04,expanding_mean_GreenRocket,expanding_mean_Door1,expanding_mean_Door2,expanding_mean_LoadCell_R02,expanding_mean_Potentiometer_R02,expanding_mean_LoadCell_R03,expanding_mean_Potentiometer_R03,expanding_mean_LoadCell_R04,expanding_mean_Potentiometer_R04
0,1,0,0,1857,11866,1693,2390,2640,11855,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,0,0,1862,11896,1679,2396,2643,11908,0.0,...,0.000000,1.000000,0.000000,0.000000,1859.500000,11881.000000,1686.000000,2393.000000,2641.500000,11881.500000
2,1,0,0,1867,11957,1669,2379,2659,11939,0.0,...,0.000000,1.000000,0.000000,0.000000,1862.000000,11906.333333,1680.333333,2388.333333,2647.333333,11900.666667
3,1,0,0,1886,11955,1699,2403,2612,11932,0.0,...,0.000000,1.000000,0.000000,0.000000,1868.000000,11918.500000,1685.000000,2392.000000,2638.500000,11908.500000
4,1,0,0,1887,11966,1670,2388,2630,11931,0.0,...,0.000000,1.000000,0.000000,0.000000,1871.800000,11928.000000,1682.000000,2391.200000,2636.800000,11913.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216029,0,0,0,1888,2061,1676,2382,2604,11801,0.0,...,11871.714286,0.027325,0.015229,0.018849,1869.839615,11245.814230,2760.599134,3642.971143,3006.628565,10718.385798
216030,0,0,0,1854,2061,1686,2404,2776,11878,0.0,...,11868.571429,0.027325,0.015229,0.018849,1869.839542,11245.771713,2760.594160,3642.965408,3006.627498,10718.391166
216031,0,0,0,1859,2073,1685,2403,3218,11917,0.0,...,11877.857143,0.027325,0.015229,0.018849,1869.839491,11245.729253,2760.589181,3642.959668,3006.628476,10718.396714
216032,0,0,0,1860,2067,1655,2385,2176,11904,0.0,...,11878.285714,0.027325,0.015229,0.018849,1869.839446,11245.686765,2760.584064,3642.953845,3006.624631,10718.402202
216033,0,0,0,1883,2071,1680,2396,3437,11906,0.0,...,11884.000000,0.027324,0.015229,0.018849,1869.839507,11245.644297,2760.579062,3642.948073,3006.626624,10718.407700

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((172827, 45), (43207, 45))

In [11]:
# Feature scaling

In [12]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])

In [13]:
# define model
model = XGBClassifier()

In [15]:
# Define SMOTE-Tomek Links
resample=SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
# Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [16]:
clf_0 = pipeline.fit(X_train, y_train)

In [17]:
pred_y_0 = clf_0.predict(X_test)

print(accuracy_score(pred_y_0, y_test))

0.9999537112042031

In [18]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_0, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00     42477
     class 1       1.00      1.00      1.00       730

    accuracy                           1.00     43207
   macro avg       1.00      1.00      1.00     43207
weighted avg       1.00      1.00      1.00     43207

array([[42476,     1],
       [    1,   729]])

In [19]:
#enn

In [20]:
# define model
model = XGBClassifier()

#Define SMOTE-ENN
resample=SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [21]:
pipeline

Pipeline(steps=[('r',
                 SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))),
                ('m',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, gpu_id=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               predictor=None, random_state=None, ...))])

In [22]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9995371120420302

In [23]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00     42477
     class 1       0.97      1.00      0.99       730

    accuracy                           1.00     43207
   macro avg       0.99      1.00      0.99     43207
weighted avg       1.00      1.00      1.00     43207

array([[42458,    19],
       [    1,   729]])

In [24]:
#ADASYN
ada = ADASYN(random_state=42)
X_res, y_res = ada.fit_resample(X, y)

In [25]:
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({1: 212528, 0: 212296})

In [26]:
model = XGBClassifier()

#Define ADASYN
resample=ADASYN(random_state=42)
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [27]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.999907422408406

In [28]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00     42477
     class 1       1.00      1.00      1.00       730

    accuracy                           1.00     43207
   macro avg       1.00      1.00      1.00     43207
weighted avg       1.00      1.00      1.00     43207

array([[42475,     2],
       [    2,   728]])