In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score

from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy.random import seed
seed(7)

from sklearn.model_selection import train_test_split

SEED = 123 #used to help randomly select the data points
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [2]:
df = pd.read_csv("processminer-rare-event-mts - data.csv") 
df.head(n=5)  # visualize the data.

,time,y,x1,x2,x3,x4,x5,x6,x7,x8,...,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61
0,5/1/99 0:00,0,0.376665,-4.596435,-4.095756,13.497687,-0.118830,-20.669883,0.000732,-0.061114,...,10.091721,0.053279,-4.936434,-24.590146,18.515436,3.473400,0.033444,0.953219,0.006076,0
1,5/1/99 0:02,0,0.475720,-4.542502,-4.018359,16.230659,-0.128733,-18.758079,0.000732,-0.061114,...,10.095871,0.062801,-4.937179,-32.413266,22.760065,2.682933,0.033536,1.090502,0.006083,0
2,5/1/99 0:04,0,0.363848,-4.681394,-4.353147,14.127997,-0.138636,-17.836632,0.010803,-0.061114,...,10.100265,0.072322,-4.937924,-34.183774,27.004663,3.537487,0.033629,1.840540,0.006090,0
3,5/1/99 0:06,0,0.301590,-4.758934,-4.023612,13.161566,-0.148142,-18.517601,0.002075,-0.061114,...,10.104660,0.081600,-4.938669,-35.954281,21.672449,3.986095,0.033721,2.554880,0.006097,0
4,5/1/99 0:08,0,0.265578,-4.749928,-4.333150,15.267340,-0.155314,-17.505913,0.000732,-0.061114,...,10.109054,0.091121,-4.939414,-37.724789,21.907251,3.601573,0.033777,1.410494,0.006105,0

In [3]:
#filter only most important 5 features
df= df[['time','y','x3','x2','x18','x17','x16','x12','x19','x54','x40','x45','x6','x11','x29','x32','x15'
        ]]
df

,time,y,x3,x2,x18,x17,x16,x12,x19,x54,x40,x45,x6,x11,x29,x32,x15
0,5/1/99 0:00,0,-4.095756,-4.596435,-0.944167,-2.327329,0.199901,-0.052959,3.075199,-4.936434,-0.720746,-0.657096,-20.669883,0.877951,-134.277860,9.366755,0.041800
1,5/1/99 0:02,0,-4.018359,-4.542502,-0.939994,-2.340627,0.304313,-0.014244,3.075199,-4.937179,-0.720746,-0.875629,-18.758079,0.873273,-134.480190,9.350215,0.041447
2,5/1/99 0:04,0,-4.353147,-4.681394,-0.935824,-2.353925,0.252839,0.065150,3.075199,-4.937924,-0.720746,-0.037775,-17.836632,1.004910,-133.946590,9.037409,0.041095
3,5/1/99 0:06,0,-4.023612,-4.758934,-0.931651,-2.367223,0.072873,-0.067199,3.075199,-4.938669,-0.720746,-0.987410,-18.517601,0.930037,-134.002590,9.020625,0.040742
4,5/1/99 0:08,0,-4.333150,-4.749928,-0.927478,-2.380521,0.171033,-0.018472,3.075199,-4.939414,-0.720746,-0.238445,-17.505913,0.828410,-133.145710,9.344233,0.040390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18393,5/28/99 23:58,0,0.406426,0.786430,-0.559565,-0.527784,-0.209548,-0.013282,-3.926967,2.682413,0.309253,-0.995204,26.300392,-0.488246,28.536469,4.159052,0.016477
18394,5/29/99 0:00,0,0.561918,0.633086,-0.567920,-0.527784,-0.098630,-0.087923,-3.926967,2.683338,0.309253,-0.635085,25.678597,-0.416892,28.082031,4.609797,0.017403
18395,5/29/99 0:02,0,0.334582,0.450126,-0.576274,-0.527784,-0.092927,-0.019256,-3.926967,2.684263,0.309253,-0.642386,25.056801,-0.391569,27.627594,4.519282,0.018329
18396,5/29/99 0:04,0,0.387263,0.419383,-0.584628,-0.527784,-0.053735,0.029572,-3.926967,2.685189,0.309253,-0.960654,24.435005,-0.341133,27.990723,4.952509,0.019254
18397,5/29/99 0:06,0,0.593416,0.582710,-0.592982,-0.527784,-0.062127,0.016245,-3.926967,2.686114,0.309253,-0.755065,24.712960,-0.386608,30.051941,5.185420,0.020180

In [4]:
sign = lambda x: (1, -1)[x < 0]

def curve_shift(df, shift_by):
    '''
    This function will shift the binary labels in a dataframe.
    The curve shift will be with respect to the 1s. 
    For example, if shift is -2, the following process
    will happen: if row n is labeled as 1, then
    - Make row (n+shift_by):(n+shift_by-1) = 1.
    - Remove row n.
    i.e. the labels will be shifted up to 2 rows up.
    
    Inputs:
    df       A pandas dataframe with a binary labeled column. 
             This labeled column should be named as 'y'.
    shift_by An integer denoting the number of rows to shift.
    
    Output
    df       A dataframe with the binary labels shifted by shift.
    '''

    vector = df['y'].copy()
    for s in range(abs(shift_by)):
        tmp = vector.shift(sign(shift_by))
        tmp = tmp.fillna(0)
        vector += tmp
    labelcol = 'y'
    # Add vector to the df
    df.insert(loc=0, column=labelcol+'tmp', value=vector)
    # Remove the rows with labelcol == 1.
    df = df.drop(df[df[labelcol] == 1].index)
    # Drop labelcol and rename the tmp col as labelcol
    df = df.drop(labelcol, axis=1)
    df = df.rename(columns={labelcol+'tmp': labelcol})
    # Make the labelcol binary
    df.loc[df[labelcol] > 0, labelcol] = 1

    return df

In [5]:
'''
Shift the data by 2 units, equal to 4 minutes.

Test: Testing whether the shift happened correctly.
'''
print('Before shifting')  # Positive labeled rows before shifting.
one_indexes = df.index[df['y'] == 1]
display(df.iloc[(one_indexes[0]-3):(one_indexes[0]+2), 0:5].head(n=5))

# Shift the response column y by 2 rows to do a 4-min ahead prediction.
df = curve_shift(df, shift_by = -2)

print('After shifting')  # Validating if the shift happened correctly.
display(df.iloc[(one_indexes[0]-4):(one_indexes[0]+1), 0:5].head(n=5))

Before shifting

             time  y         x3         x2        x18
256   5/1/99 8:32  0  -1.097158  -4.058394  -2.261420
257   5/1/99 8:34  0  -1.074373  -3.876199  -2.279643
258   5/1/99 8:36  0  -1.249954  -3.868467  -2.297866
259   5/1/99 8:38  1 -10.006578 -13.332664 -10.918982
260  5/1/99 10:50  0  -1.248529  -3.987897  -4.511733

After shifting

       y          time        x3        x2       x18
255  0.0   5/1/99 8:30 -1.133779 -3.865720 -2.243193
256  0.0   5/1/99 8:32 -1.097158 -4.058394 -2.261420
257  1.0   5/1/99 8:34 -1.074373 -3.876199 -2.279643
258  1.0   5/1/99 8:36 -1.249954 -3.868467 -2.297866
260  0.0  5/1/99 10:50 -1.248529 -3.987897 -4.511733

In [6]:
# Remove time column, and the categorical columns
df = df.drop(['time'], axis=1)

In [7]:
X = df.drop(['y'], axis=1)

y = df['y']

In [8]:
X

,x3,x2,x18,x17,x16,x12,x19,x54,x40,x45,x6,x11,x29,x32,x15
0,-4.095756,-4.596435,-0.944167,-2.327329,0.199901,-0.052959,3.075199,-4.936434,-0.720746,-0.657096,-20.669883,0.877951,-134.277860,9.366755,0.041800
1,-4.018359,-4.542502,-0.939994,-2.340627,0.304313,-0.014244,3.075199,-4.937179,-0.720746,-0.875629,-18.758079,0.873273,-134.480190,9.350215,0.041447
2,-4.353147,-4.681394,-0.935824,-2.353925,0.252839,0.065150,3.075199,-4.937924,-0.720746,-0.037775,-17.836632,1.004910,-133.946590,9.037409,0.041095
3,-4.023612,-4.758934,-0.931651,-2.367223,0.072873,-0.067199,3.075199,-4.938669,-0.720746,-0.987410,-18.517601,0.930037,-134.002590,9.020625,0.040742
4,-4.333150,-4.749928,-0.927478,-2.380521,0.171033,-0.018472,3.075199,-4.939414,-0.720746,-0.238445,-17.505913,0.828410,-133.145710,9.344233,0.040390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18393,0.406426,0.786430,-0.559565,-0.527784,-0.209548,-0.013282,-3.926967,2.682413,0.309253,-0.995204,26.300392,-0.488246,28.536469,4.159052,0.016477
18394,0.561918,0.633086,-0.567920,-0.527784,-0.098630,-0.087923,-3.926967,2.683338,0.309253,-0.635085,25.678597,-0.416892,28.082031,4.609797,0.017403
18395,0.334582,0.450126,-0.576274,-0.527784,-0.092927,-0.019256,-3.926967,2.684263,0.309253,-0.642386,25.056801,-0.391569,27.627594,4.519282,0.018329
18396,0.387263,0.419383,-0.584628,-0.527784,-0.053735,0.029572,-3.926967,2.685189,0.309253,-0.960654,24.435005,-0.341133,27.990723,4.952509,0.019254
18397,0.593416,0.582710,-0.592982,-0.527784,-0.062127,0.016245,-3.926967,2.686114,0.309253,-0.755065,24.712960,-0.386608,30.051941,5.185420,0.020180

In [9]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((14619, 15), (3655, 15))

In [10]:
# Feature scaling

In [11]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])

In [12]:
# define model
model = XGBClassifier()
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.90965

In [13]:
model = XGBClassifier()
clf_0 = model.fit(X_train, y_train)

In [14]:
pred_y_0 = clf_0.predict(X_test)
print(accuracy_score(pred_y_0, y_test))

0.9868673050615595

In [15]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_0, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

     class 0       0.99      1.00      0.99      3608
     class 1       0.40      0.04      0.08        47

    accuracy                           0.99      3655
   macro avg       0.69      0.52      0.54      3655
weighted avg       0.98      0.99      0.98      3655

array([[3605,    3],
       [  45,    2]])

# Weighted XGBoost for Class Imbalance

In [16]:
# define model
#scale_pos_weight=total_negative_examples / total_positive_examples
#total number of examples in the majority class / total number of examples in the minority class.
#18274/124=147.37
model = XGBClassifier(scale_pos_weight=147)

# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.89645

In [17]:
clf_1 = model.fit(X_train, y_train)
pred_y_1 = clf_1.predict(X_test)

print(accuracy_score(pred_y_1, y_test))

0.986593707250342

In [18]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_1, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_1)

              precision    recall  f1-score   support

     class 0       0.99      1.00      0.99      3608
     class 1       0.46      0.28      0.35        47

    accuracy                           0.99      3655
   macro avg       0.73      0.64      0.67      3655
weighted avg       0.98      0.99      0.98      3655

array([[3593,   15],
       [  34,   13]])

# Tune with GridSearch CV

In [19]:
# define grid
weights = [1, 10, 25, 50, 75, 99, 100, 1000]
param_grid = dict(scale_pos_weight=weights)

In [20]:
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='roc_auc')

In [33]:
# execute the grid search
grid_result = grid.fit(X, y)
# report the best configuration
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# report all configurations
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

/Users/chathurangishyalika/opt/anaconda3/envs/tf/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[13:03:30] WARNING: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_44tbtwf8c1/croots/recipe/xgboost-split_1659548960882/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Best: 0.931436 using {'scale_pos_weight': 1}
0.931436 (0.040774) with: {'scale_pos_weight': 1}
0.927670 (0.048305) with: {'scale_pos_weight': 10}
0.929479 (0.045071) with: {'scale_pos_weight': 25}
0.922069 (0.046362) with: {'scale_pos_weight': 50}
0.923126 (0.051366) with: {'scale_pos_weight': 75}
0.922714 (0.053929) with: {'scale_pos_weight': 99}
0.922413 (0.053952) with: {'scale_pos_weight': 100}
0.905774 (0.058887) with: {'scale_pos_weight': 1000}

In [21]:
# define model
model = XGBClassifier(scale_pos_weight=1000)

# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.86855

In [22]:
clf_2 = model.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9816689466484269

In [23]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       0.99      0.99      0.99      3608
     class 1       0.31      0.36      0.34        47

    accuracy                           0.98      3655
   macro avg       0.65      0.68      0.66      3655
weighted avg       0.98      0.98      0.98      3655

array([[3571,   37],
       [  30,   17]])