In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score

from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean

from numpy.random import seed
seed(7)

from sklearn.model_selection import train_test_split

SEED = 123 #used to help randomly select the data points
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [10]:
df = pd.read_csv("processminer-rare-event-mts - data.csv") 
df  # visualize the data.

,time,y,x1,x2,x3,x4,x5,x6,x7,x8,...,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61
0,5/1/99 0:00,0,0.376665,-4.596435,-4.095756,13.497687,-0.118830,-20.669883,0.000732,-0.061114,...,10.091721,0.053279,-4.936434,-24.590146,18.515436,3.473400,0.033444,0.953219,0.006076,0
1,5/1/99 0:02,0,0.475720,-4.542502,-4.018359,16.230659,-0.128733,-18.758079,0.000732,-0.061114,...,10.095871,0.062801,-4.937179,-32.413266,22.760065,2.682933,0.033536,1.090502,0.006083,0
2,5/1/99 0:04,0,0.363848,-4.681394,-4.353147,14.127997,-0.138636,-17.836632,0.010803,-0.061114,...,10.100265,0.072322,-4.937924,-34.183774,27.004663,3.537487,0.033629,1.840540,0.006090,0
3,5/1/99 0:06,0,0.301590,-4.758934,-4.023612,13.161566,-0.148142,-18.517601,0.002075,-0.061114,...,10.104660,0.081600,-4.938669,-35.954281,21.672449,3.986095,0.033721,2.554880,0.006097,0
4,5/1/99 0:08,0,0.265578,-4.749928,-4.333150,15.267340,-0.155314,-17.505913,0.000732,-0.061114,...,10.109054,0.091121,-4.939414,-37.724789,21.907251,3.601573,0.033777,1.410494,0.006105,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18393,5/28/99 23:58,0,-0.877441,0.786430,0.406426,135.301215,0.112295,26.300392,-0.159185,0.058823,...,-0.773514,-0.752385,2.682413,6.944644,-37.795661,-0.860218,0.010220,0.895685,-0.011242,0
18394,5/29/99 0:00,0,-0.843988,0.633086,0.561918,133.228949,0.141332,25.678597,-0.159185,0.058823,...,-0.773514,-0.752385,2.683338,0.507755,-39.357199,-0.915698,0.010620,0.175348,-0.011235,0
18395,5/29/99 0:02,0,-0.826547,0.450126,0.334582,134.977973,0.170370,25.056801,-0.159185,0.048752,...,-0.773514,-0.752385,2.684263,2.809146,-39.357199,-1.409596,0.013323,0.621020,-0.011228,0
18396,5/29/99 0:04,0,-0.822843,0.419383,0.387263,135.658942,0.199422,24.435005,-0.159185,0.048752,...,-0.773514,-0.752385,2.685189,2.164859,-39.357199,-0.860218,0.012888,1.390902,-0.011221,0
18397,5/29/99 0:06,0,-0.840981,0.582710,0.593416,136.339880,0.228460,24.712960,-0.159185,0.048752,...,-0.773514,-0.752385,2.686114,1.416690,-39.357199,-0.732044,0.012453,0.418993,-0.011214,0

In [11]:
index_lower_limit = 4177
index_upper_limit = 11503

df = pd.DataFrame(df[index_lower_limit: index_upper_limit])
df

,time,y,x1,x2,x3,x4,x5,x6,x7,x8,...,x52,x53,x54,x55,x56,x57,x58,x59,x60,x61
4177,5/7/99 13:28,1,-3.787279,-8.936167,-9.729623,-214.34934,0.062673,-125.748970,-0.429273,-0.451141,...,-6.762039,-6.856144,2.770261,77.176578,-63.714026,-1.379077,0.035358,-0.148451,0.004919,0
4178,5/7/99 13:34,0,-1.632907,8.798339,-5.254108,-176.88787,-0.086024,-86.578254,-0.429273,-0.085388,...,-6.777176,-6.856144,2.768471,-4.437069,-30.676032,-1.226428,0.027404,0.294268,0.004806,0
4179,5/7/99 13:36,0,-2.027379,8.666358,5.840922,-179.27187,-0.086024,-77.143959,-0.076540,-0.071186,...,-6.782303,-6.856144,2.767874,11.403385,-22.480460,-2.047413,0.027073,0.782915,0.004769,0
4180,5/7/99 13:38,0,-0.619546,6.910144,7.031393,-177.13259,-0.086024,-73.890693,-0.069155,-0.071186,...,-6.787430,-6.856144,2.767277,17.182804,-22.480460,-2.111499,0.026741,1.320841,0.004731,0
4181,5/7/99 13:40,0,-1.019356,7.319770,7.415930,-179.34461,-0.098994,-72.566185,-0.069155,-0.071186,...,-6.792557,-6.856144,2.766681,16.881412,-28.256201,-2.721852,0.023750,0.659441,0.004694,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11498,5/18/99 4:14,0,0.257948,-4.848939,3.191914,-322.78161,-0.671366,-279.408440,0.050782,0.058823,...,4.262131,9.166072,3.057857,38.565738,-269.039500,2.557811,-0.149790,0.241167,0.004274,0
11499,5/18/99 4:16,0,0.346350,-4.752980,3.282870,-322.78161,-0.701014,-279.408440,0.054475,0.048752,...,4.262131,9.166072,3.055969,42.917301,-269.039500,3.168224,-0.149790,0.038065,0.004283,0
11500,5/18/99 4:18,0,0.518950,-4.811716,3.433512,-322.78161,-0.445338,-279.408440,0.060853,0.058823,...,4.262131,9.166072,3.054080,44.334781,-269.039500,2.557811,-0.149790,0.617220,0.004293,0
11501,5/18/99 4:20,0,0.810028,-4.795506,3.363568,-322.78161,-0.174662,-279.408440,0.060853,0.049759,...,4.262131,9.166072,3.052192,40.161685,-269.039500,2.557811,-0.149790,1.233729,0.004302,0
11502,5/18/99 4:22,0,0.964779,-4.992426,3.795181,-322.78161,0.096029,-279.408440,0.060853,0.048752,...,4.262131,9.166072,3.050304,46.497867,-269.039500,2.109203,-0.149790,0.234987,0.004311,0

In [12]:
df['y'].value_counts()[1]

38

In [13]:
df['y'].value_counts()[0]

7288

In [14]:
sign = lambda x: (1, -1)[x < 0]

def curve_shift(df, shift_by):
    '''
    This function will shift the binary labels in a dataframe.
    The curve shift will be with respect to the 1s. 
    For example, if shift is -2, the following process
    will happen: if row n is labeled as 1, then
    - Make row (n+shift_by):(n+shift_by-1) = 1.
    - Remove row n.
    i.e. the labels will be shifted up to 2 rows up.
    
    Inputs:
    df       A pandas dataframe with a binary labeled column. 
             This labeled column should be named as 'y'.
    shift_by An integer denoting the number of rows to shift.
    
    Output
    df       A dataframe with the binary labels shifted by shift.
    '''

    vector = df['y'].copy()
    for s in range(abs(shift_by)):
        tmp = vector.shift(sign(shift_by))
        tmp = tmp.fillna(0)
        vector += tmp
    labelcol = 'y'
    # Add vector to the df
    df.insert(loc=0, column=labelcol+'tmp', value=vector)
    # Remove the rows with labelcol == 1.
    df = df.drop(df[df[labelcol] == 1].index)
    # Drop labelcol and rename the tmp col as labelcol
    df = df.drop(labelcol, axis=1)
    df = df.rename(columns={labelcol+'tmp': labelcol})
    # Make the labelcol binary
    df.loc[df[labelcol] > 0, labelcol] = 1

    return df

In [15]:
'''
Shift the data by 2 units, equal to 4 minutes.

Test: Testing whether the shift happened correctly.
'''
print('Before shifting')  # Positive labeled rows before shifting.
one_indexes = df.index[df['y'] == 1]
display(df.iloc[(one_indexes[0]-3):(one_indexes[0]+2), 0:5].head(n=5))

# Shift the response column y by 2 rows to do a 4-min ahead prediction.
df = curve_shift(df, shift_by = -2)

print('After shifting')  # Validating if the shift happened correctly.
display(df.iloc[(one_indexes[0]-4):(one_indexes[0]+1), 0:5].head(n=5))

Before shifting

               time  y        x1        x2        x3
8351  5/13/99 14:06  0  1.320275  0.863326 -6.387846
8352  5/13/99 14:08  0  1.301173  0.752034 -6.449086
8353  5/13/99 14:10  0  1.319648  0.628083 -6.286384
8354  5/13/99 14:12  0  1.304881  0.643592 -6.367684
8355  5/13/99 14:14  0  1.313052  0.590009 -6.173917

After shifting

        y           time        x1        x2        x3
8369  0.0  5/13/99 14:42  1.301987  0.509212 -6.585966
8370  0.0  5/13/99 14:44  1.222639  0.484897 -6.567905
8371  0.0  5/13/99 14:46  1.202801  0.554038 -6.677771
8372  0.0  5/13/99 14:48  1.253957  0.661002 -6.805399
8373  0.0  5/13/99 14:50  1.275130  0.374429 -6.694682

In [16]:
# Remove time column, and the categorical columns
df = df.drop(['time', 'x28', 'x61'], axis=1)

In [17]:
X = df.drop(['y'], axis=1)

y = df['y']

In [18]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((5830, 59), (1458, 59))

In [19]:
y_train

7711     0.0
10700    0.0
7567     0.0
9295     0.0
11347    0.0
        ...
9130     0.0
7450     0.0
5834     0.0
6789     0.0
6915     0.0
Name: y, Length: 5830, dtype: float64

In [20]:
# Feature scaling

In [21]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])

In [22]:
# define model
model = XGBClassifier()
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.95236

In [23]:
model = XGBClassifier()

clf_0 = model.fit(X_train, y_train)

In [24]:
pred_y_0 = clf_0.predict(X_test)

print(accuracy_score(pred_y_0, y_test))

0.9883401920438958

In [25]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_0, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

     class 0       0.99      1.00      0.99      1442
     class 1       0.00      0.00      0.00        16

    accuracy                           0.99      1458
   macro avg       0.49      0.50      0.50      1458
weighted avg       0.98      0.99      0.98      1458

array([[1441,    1],
       [  16,    0]])

# Weighted XGBoost for Class Imbalance

In [26]:
# define model
#scale_pos_weight=total_negative_examples / total_positive_examples
#total number of examples in the majority class / total number of examples in the minority class.
#18274/124=147.37
model = XGBClassifier(scale_pos_weight=147)

# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.93074

In [27]:
clf_1 = model.fit(X_train, y_train)
pred_y_1 = clf_1.predict(X_test)

print(accuracy_score(pred_y_1, y_test))

0.9849108367626886

In [28]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_1, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_1)

              precision    recall  f1-score   support

     class 0       0.99      1.00      0.99      1442
     class 1       0.00      0.00      0.00        16

    accuracy                           0.98      1458
   macro avg       0.49      0.50      0.50      1458
weighted avg       0.98      0.98      0.98      1458

array([[1436,    6],
       [  16,    0]])

# Tune with GridSearch CV

In [29]:
# define grid
weights = [1, 10, 25, 50, 75, 99, 100, 1000]
param_grid = dict(scale_pos_weight=weights)

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# define grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=cv, scoring='roc_auc')

In [33]:
# execute the grid search
grid_result = grid.fit(X, y)
# report the best configuration
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
# report all configurations
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

/Users/chathurangishyalika/opt/anaconda3/envs/tf/lib/python3.7/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[13:03:30] WARNING: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_44tbtwf8c1/croots/recipe/xgboost-split_1659548960882/work/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Best: 0.931436 using {'scale_pos_weight': 1}
0.931436 (0.040774) with: {'scale_pos_weight': 1}
0.927670 (0.048305) with: {'scale_pos_weight': 10}
0.929479 (0.045071) with: {'scale_pos_weight': 25}
0.922069 (0.046362) with: {'scale_pos_weight': 50}
0.923126 (0.051366) with: {'scale_pos_weight': 75}
0.922714 (0.053929) with: {'scale_pos_weight': 99}
0.922413 (0.053952) with: {'scale_pos_weight': 100}
0.905774 (0.058887) with: {'scale_pos_weight': 1000}

In [46]:
# define model
model = XGBClassifier(scale_pos_weight=1000)

# define evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate model
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
# summarize performance
print('Mean ROC AUC: %.5f' % mean(scores))

Mean ROC AUC: 0.92884

In [47]:
clf_2 = model.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.99039780521262

In [48]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       0.99      1.00      1.00      1442
     class 1       0.62      0.31      0.42        16

    accuracy                           0.99      1458
   macro avg       0.81      0.66      0.71      1458
weighted avg       0.99      0.99      0.99      1458

array([[1439,    3],
       [  11,    5]])