In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split

SEED = 123 
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [12]:
df=pd.read_csv("APS_selected_without_null.csv")
df

,Unnamed: 0,bj_000,ci_000,ay_002,ag_001,ay_005,ag_002,am_0,ay_006,ee_003,...,cs_002,aq_000,bf_000,at_000,ee_005,bb_000,bl_000,ee_000,bo_000,bk_000
0,0,799478.0,5245752.00,2198.356,828.488,469014.000000,8571.650,107278.622,4.239660e+06,493384.0,...,267998.0,1132040.0,50.000000,6709.982,469792.0,6700214.0,353400.000000,965866.0,283680.00,330760.00
1,1,392208.0,2291079.36,0.000,0.000,71510.000000,0.000,0.000,7.727200e+05,178064.0,...,164860.0,338544.0,350.000000,0.000,245416.0,3646660.0,359780.000000,664504.0,189120.00,341420.00
2,2,139730.0,2322692.16,0.000,0.000,202696.500000,0.000,486.750,8.704560e+05,159812.0,...,56362.0,153698.0,4.000000,0.000,409564.0,2673338.0,130640.000000,262032.0,106380.00,137160.00
3,3,3090.0,2135.04,0.000,0.000,181363.333333,0.000,3894.000,1.781648e+06,46.0,...,24.0,1014.0,107.933333,0.000,44.0,21614.0,253274.666667,5670.0,75648.00,246502.00
4,4,399410.0,3565684.80,0.000,0.000,372236.000000,0.000,811.250,2.128914e+06,229790.0,...,80950.0,551022.0,2.000000,0.000,347188.0,4289260.0,282560.000000,404740.0,59100.00,306780.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,59995,678792.0,8289544.32,5757.992,1061.362,45114.000000,6691.674,2114.000,2.533260e+06,566884.0,...,138036.0,776370.0,14.000000,1574.588,1218244.0,10845228.0,221620.000000,1608808.0,152420.00,263320.00
59996,59996,9572.0,123344.64,5757.992,1061.362,4610.000000,6691.674,76769.085,9.912000e+04,6760.0,...,3606.0,11622.0,66.645000,1574.588,68424.0,147638.0,163342.460000,13934.0,99662.58,160036.47
59997,59997,6224.0,7518.72,5757.992,1061.362,137882.849000,6691.674,76768.344,1.062160e+06,386.0,...,72.0,874.0,66.671000,1603.238,144.0,43738.0,163508.610000,15876.0,99843.76,160040.61
59998,59998,1032454.0,4776505.92,5757.992,1061.362,119742.000000,6691.558,76758.797,4.445146e+06,222654.0,...,333922.0,1214970.0,70.000000,57300.000,225724.0,6159728.0,332300.000000,1180714.0,362360.00,302700.00
59999,59999,260378.0,2480113.92,0.000,0.000,105702.000000,0.000,0.000,1.433988e+06,183200.0,...,81228.0,334864.0,2.000000,0.000,254068.0,3076406.0,268280.000000,409798.0,0.00,191320.00

# without curve-shifting

In [13]:
df = df.drop(['Unnamed: 0'], axis=1)

In [14]:
df1 = pd.read_csv('aps_failure_training_set.csv')
df1
df1['class'] = df1['class'].replace({'pos': 1, 'neg': 0})
df1
y = df1['class']

y=y.fillna(0)
y

0        0
1        0
2        0
3        0
4        0
        ..
59995    0
59996    0
59997    0
59998    0
59999    0
Name: class, Length: 60000, dtype: int64

In [15]:
input_X = df  

n_features = input_X.shape[1]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(input_X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((48000, 58), (12000, 58))

In [17]:
# Feature scaling

In [18]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])

In [20]:
clf_0 = LogisticRegression().fit(input_X, y)

/Users/chathurangishyalika/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
# Predict on training set
pred_y_0 = clf_0.predict(X_test)
print(accuracy_score(pred_y_0, y_test))

0.38233333333333336

/Users/chathurangishyalika/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [22]:
target_names = LABELS
print(classification_report(y_test, pred_y_0, target_names=target_names))

confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

      Normal       0.99      0.38      0.54     11816
       Break       0.02      0.82      0.04       184

    accuracy                           0.38     12000
   macro avg       0.51      0.60      0.29     12000
weighted avg       0.98      0.38      0.54     12000

array([[4437, 7379],
       [  33,  151]])

In [23]:
clf = RandomForestClassifier(max_depth=100, random_state=0)
clf_0 = clf.fit(X_train, y_train)
pred_y_0 = clf_0.predict(X_test)
print(accuracy_score(pred_y_0, y_test))

0.9940833333333333

In [24]:
target_names = LABELS
print(classification_report(y_test, pred_y_0, target_names=target_names))

confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00     11816
       Break       0.91      0.68      0.78       184

    accuracy                           0.99     12000
   macro avg       0.95      0.84      0.89     12000
weighted avg       0.99      0.99      0.99     12000

array([[11804,    12],
       [   59,   125]])